@echo off
echo Stage 6B: Anchor-Faithful Unified Differentiable PhysarumPose
python 72_train_anchor_faithful_physarum_pose.py --crop_csv outputs/stage5g_target_person_crop_filter/crop_metadata.csv --annotation_csv outputs/stage4b_strong_anchor_predictions/strong_anchor_predictions.csv --image_dir data/processed/synth_occlusion_mpii/images --out_dir outputs/stage6b_anchor_faithful_physarum_pose --epochs 120 --batch_size 16 --input_size 256 --anchor_warmup_epochs 35
python 73_evaluate_anchor_faithful_physarum_pose.py --crop_csv outputs/stage5g_target_person_crop_filter/crop_metadata.csv --annotation_csv outputs/stage4b_strong_anchor_predictions/strong_anchor_predictions.csv --image_dir data/processed/synth_occlusion_mpii/images --model_dir outputs/stage6b_anchor_faithful_physarum_pose --out_dir outputs/stage6b_anchor_faithful_physarum_pose/eval --batch_size 16
python 74_visualize_anchor_faithful_physarum_pose.py --pred_csv outputs/stage6b_anchor_faithful_physarum_pose/eval/anchor_faithful_predictions.csv --topk_csv outputs/stage6b_anchor_faithful_physarum_pose/eval/anchor_faithful_topk_predictions.csv --image_dir data/processed/synth_occlusion_mpii/images --out_dir outputs/stage6b_anchor_faithful_physarum_pose/eval/visualizations --max_images 150
python 74_visualize_anchor_faithful_physarum_pose.py --pred_csv outputs/stage6b_anchor_faithful_physarum_pose/eval/anchor_faithful_predictions.csv --topk_csv outputs/stage6b_anchor_faithful_physarum_pose/eval/anchor_faithful_topk_predictions.csv --image_dir data/processed/synth_occlusion_mpii/images --out_dir outputs/stage6b_anchor_faithful_physarum_pose/eval/presentation_images --max_images 80 --only_good
python 75_make_stage6b_report_text.py --summary_csv outputs/stage6b_anchor_faithful_physarum_pose/eval/anchor_faithful_summary.csv --by_target_csv outputs/stage6b_anchor_faithful_physarum_pose/eval/anchor_faithful_summary_by_target.csv --out_txt outputs/stage6b_anchor_faithful_physarum_pose/eval/stage6b_report_text.txt
echo Done.
pause
